### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#958]
## Todo

- [x] release notes
- [x] remove feature flags for CUD
- [ ] branch for v `release-3.0.0` 
- [ ] update build numbers on new branch
- [ ] upload to beta testers
- [ ] create deobfuscation in Play Store and Sentry
- [ ] create [prod request](https://bugzilla.mozilla.org/show_bug.cgi?id=1581957) 

## Rollout schedule

- [ ] 100% on beta - Oct 16-18
- [ ] 20% on prod. - Oct 21
- [ ] 100% on prod - Oct 22

**Comment by eliserichards** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1590455
